### PR TITLE
fixed unexpected end of input error

### PR DESCRIPTION
**Pull request by paawaaa**

### CODE REVIEW

**Comment by OldBlackJoe** [comment]
I unpublished version 0.6.4.

**Comment by paawaaa** [comment]
What's next? You merge the last PR and then publish 0.6.4 again, or what? Why you unpublished version 0.6.4?

**Comment by OldBlackJoe** [comment]
I think this change is tiny so I merge this PR and republish version 0.6.4 tonight.
Because I'm working now, it's hard to publish at work. sorry for confusing.

**Comment by OldBlackJoe** [comment]
@paawaaa 
I'm sorry, you were right.
I overlooked that NPM never allowed to publish a package with the same version. (0.6.4)
So I have released your PR version 0.6.5. Sorry for confusing.

**Pull request merged**
